# Generated by Django 5.0.4 on 2024-07-06 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pendientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=128)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('priority', models.CharField(choices=[('ALTA', 'ALT'), ('MEDIA', 'MD'), ('BAJA', 'BJ')], max_length=8)),
                ('state', models.CharField(choices=[('SIN_RESOLVER', 'NS'), ('PENDIENTE', 'DG'), ('RESUELTO', 'DN')], max_length=16)),
                ('status', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
