# Generated by Django 5.0.4 on 2024-07-07 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendientes',
            name='state',
            field=models.CharField(choices=[('SIN_RESOLVER', 'Sin resolver'), ('PENDIENTE', 'Pendiente'), ('RESUELTO', 'Resuelto')], max_length=16),
        ),
    ]
